CREATE TABLE BenJHall.members(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	forename VARCHAR(40) NOT NULL,
	surname VARCHAR(40) NOT NULL,
	gender VARCHAR(1) NOT NULL,
	email VARCHAR(50) NOT NULL,
	hashPassword CHAR(128) NOT NULL, 
	salt VARCHAR(40) NOT NULL,
	joinDate DATETIME NOT NULL,
	admin TINYINT(1) NOT NULL,
	accountActive TINYINT(1) NOT NULL
) ENGINE = InnoDB;